#!/bin/bash
rsync -vvzuae ssh jQueryUI/ wessel@asdf-systems.de:/var/www/www.asdf-systems.de/webengine 
rsync -vvzuae ssh ../../src/ wessel@asdf-systems.de:/var/www/www.asdf-systems.de/webengine/src
ssh wessel@asdf-systems.de 'sudo chmod 0777 -R /var/www/www.asdf-systems.de/webengine'
